version: '2.4'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: updb
      POSTGRES_USER: upuser
      POSTGRES_PASSWORD: uppassword

    ports:
      - "5432:5432"
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


#  nginx:
#    image: nginx:latest
#    container_name: nginx_container
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - postgres

volumes:
  postgres_data:
