spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create-drop
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/updb
  username: upuser
  password: uppassword

spring:
  sql:
    init:
      platform: postgres

quote:
  api:
    brapi:
      url-quote: "https://brapi.dev/api/"
      key-name: "Authorization"
      key-value: "XXXXXXXXXXXXX"